<a href="https://colab.research.google.com/github/Rushabh309/-Data-Preprocessing/blob/main/Data_Preprocessing_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("top2018.csv")

In [3]:
data.head()

id  ... time_signature
0  6DCZcSspjsKoFjzjrWoCd  ...            4.0
1  3ee8Jmje8o58CHK66QrVC  ...            4.0
2  0e7ipj03S05BNilyu5bRz  ...            4.0
3  3swc6WTsr7rl9DqQKQA55  ...            4.0
4  2G7V7zsVDxg1yRsu7Ew9R  ...            4.0

[5 rows x 16 columns]

In [4]:
data.shape

(100, 16)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id                100 non-null    object 
 1   name              100 non-null    object 
 2   artists           100 non-null    object 
 3   danceability      100 non-null    float64
 4   energy            100 non-null    float64
 5   key               100 non-null    float64
 6   loudness          100 non-null    float64
 7   mode              100 non-null    float64
 8   speechiness       100 non-null    float64
 9   acousticness      100 non-null    float64
 10  instrumentalness  100 non-null    float64
 11  liveness          100 non-null    float64
 12  valence           100 non-null    float64
 13  tempo             100 non-null    float64
 14  duration_ms       100 non-null    float64
 15  time_signature    100 non-null    float64
dtypes: float64(13), object(3)
memory usage: 12.6+

In [6]:
data.describe()

danceability      energy  ...    duration_ms  time_signature
count     100.00000  100.000000  ...     100.000000          100.00
mean        0.71646    0.659060  ...  205206.780000            3.98
std         0.13107    0.145067  ...   40007.893404            0.20
min         0.25800    0.296000  ...   95467.000000            3.00
25%         0.63550    0.562000  ...  184680.000000            4.00
50%         0.73300    0.678000  ...  205047.500000            4.00
75%         0.79825    0.772250  ...  221493.250000            4.00
max         0.96400    0.909000  ...  417920.000000            5.00

[8 rows x 13 columns]

In [7]:
data.isnull().sum()

id                  0
name                0
artists             0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
duration_ms         0
time_signature      0
dtype: int64

In [8]:
data.columns

Index(['id', 'name', 'artists', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature'],
      dtype='object')

In [9]:
data = data.drop(labels='id',axis=1)

In [10]:
data['name'].value_counts().sum()

100

In [11]:
data['artists'].value_counts().sum()

100

In [12]:
X = data.iloc[:, [3,5,8,9]].values
y = data.iloc[:, 2].values

In [13]:
from sklearn.preprocessing import LabelEncoder
labelEncoderX = LabelEncoder()
X[:,0] = labelEncoderX.fit_transform(X[:,0])

In [14]:
print(X)

[[ 1.1000e+01 -9.2110e+00  3.3200e-02  8.2900e-05]
 [ 3.2000e+01 -4.8800e+00  2.5800e-01  3.7200e-03]
 [ 1.7000e+01 -6.0900e+00  1.1700e-01  6.5600e-05]
 [ 2.3000e+01 -8.0110e+00  5.8000e-01  0.0000e+00]
 [ 3.5000e+01 -5.8330e+00  5.8900e-02  6.0000e-05]
 [ 2.4000e+01 -5.8430e+00  3.5400e-01  0.0000e+00]
 [ 5.9000e+01 -3.9980e+00  9.9000e-02  0.0000e+00]
 [ 9.2000e+01 -3.2400e+00  3.7000e-02  2.1900e-05]
 [ 2.2000e+01 -5.9750e+00  4.0300e-02  0.0000e+00]
 [ 9.3000e+01 -2.3840e+00  2.0500e-01  0.0000e+00]
 [ 1.5000e+01 -4.3330e+00  1.8400e-01  3.5600e-05]
 [ 2.5000e+01 -7.2300e+00  3.4900e-01  0.0000e+00]
 [ 9.6000e+01 -6.4740e+00  8.9100e-02  1.0900e-04]
 [ 2.1000e+01 -6.8250e+00  5.6800e-01  0.0000e+00]
 [ 4.3000e+01 -3.0610e+00  1.7100e-01  0.0000e+00]
 [ 3.7000e+01 -4.9460e+00  6.0500e-02  1.9400e-04]
 [ 5.6000e+01 -5.5070e+00  4.0000e-02  3.1100e-06]
 [ 7.2000e+01 -4.7360e+00  3.6400e-02  1.0800e-03]
 [ 1.8000e+01 -5.7230e+00  5.5600e-01  4.0400e-03]
 [ 2.7000e+01 -7.4950e+00  1.04

In [15]:
data_one = X[:2]

In [16]:
dummy = pd.get_dummies(data['name'])
dummy.head()

1, 2, 3 (feat. Jason Derulo & De La Ghetto)  ...  rockstar (feat. 21 Savage)
0                                            0  ...                           0
1                                            0  ...                           0
2                                            0  ...                           1
3                                            0  ...                           0
4                                            0  ...                           0

[5 rows x 100 columns]

In [17]:
data = pd.concat([data,dummy],axis='columns')
data.head()

name  ... rockstar (feat. 21 Savage)
0                    God's Plan  ...                          0
1                          SAD!  ...                          0
2    rockstar (feat. 21 Savage)  ...                          1
3  Psycho (feat. Ty Dolla $ign)  ...                          0
4                In My Feelings  ...                          0

[5 rows x 115 columns]

In [18]:
dummy = pd.get_dummies(data['artists'])
dummy.head()

5 Seconds of Summer  6ix9ine  Anitta  ...  Zac Efron  Zedd  benny blanco
0                    0        0       0  ...          0     0             0
1                    0        0       0  ...          0     0             0
2                    0        0       0  ...          0     0             0
3                    0        0       0  ...          0     0             0
4                    0        0       0  ...          0     0             0

[5 rows x 70 columns]

In [19]:
data = pd.concat([data,dummy],axis='columns')
data.head()

name       artists  ...  Zedd  benny blanco
0                    God's Plan         Drake  ...     0             0
1                          SAD!  XXXTENTACION  ...     0             0
2    rockstar (feat. 21 Savage)   Post Malone  ...     0             0
3  Psycho (feat. Ty Dolla $ign)   Post Malone  ...     0             0
4                In My Feelings         Drake  ...     0             0

[5 rows x 185 columns]

In [20]:
data = data.drop(['name','artists'],axis=1)

In [21]:
data.head()

danceability  energy  key  loudness  ...  ZAYN  Zac Efron  Zedd  benny blanco
0         0.754   0.449  7.0    -9.211  ...     0          0     0             0
1         0.740   0.613  8.0    -4.880  ...     0          0     0             0
2         0.587   0.535  5.0    -6.090  ...     0          0     0             0
3         0.739   0.559  8.0    -8.011  ...     0          0     0             0
4         0.835   0.626  1.0    -5.833  ...     0          0     0             0

[5 rows x 183 columns]

In [22]:
data.shape

(100, 183)

In [23]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
data_ss = ss.fit_transform(data)
data_ss

array([[ 0.28785442, -1.45531381,  0.4565313 , ..., -0.10050378,
        -0.10050378, -0.10050378],
       [ 0.18050328, -0.31910766,  0.72990334, ..., -0.10050378,
        -0.10050378, -0.10050378],
       [-0.99269134, -0.85949839, -0.09021277, ..., -0.10050378,
        -0.10050378, -0.10050378],
       ...,
       [-1.2610692 ,  0.69932103, -1.45707297, ..., -0.10050378,
        -0.10050378, -0.10050378],
       [-3.51544317, -1.53845085,  1.55001946, ..., -0.10050378,
        -0.10050378, -0.10050378],
       [-1.25340126, -0.50616599,  1.55001946, ..., -0.10050378,
        -0.10050378, -0.10050378]])

In [24]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
data_mm = mm.fit_transform(data)
data_mm

array([[0.70254958, 0.24959217, 0.63636364, ..., 0.        , 0.        ,
        0.        ],
       [0.68271955, 0.51712887, 0.72727273, ..., 0.        , 0.        ,
        0.        ],
       [0.46600567, 0.38988581, 0.45454545, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.41643059, 0.75693312, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.23001631, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.41784703, 0.4730832 , 1.        , ..., 0.        , 0.        ,
        0.        ]])